name: Test
on: push
jobs:
  buildTest:
    runs-on: ubuntu-latest
    steps:
      - name: Download git
        uses: actions/checkout@v3
      - name: Update kernel
        run: sudo apt-get update && sudo apt-get install -y
      - name: Download dependencies
        run: sudo apt install gcc gcc-i686-linux-gnu nasm build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo
      - name: Dnstall i686-elf-gcc
        run: |
          wget https://github.com/Alex9600t/gcc-i686/releases/download/rel_1/part_aa
          wget https://github.com/Alex9600t/gcc-i686/releases/download/rel_1/part_ab
          wget https://github.com/Alex9600t/gcc-i686/releases/download/rel_1/part_ac
          wget https://github.com/Alex9600t/gcc-i686/releases/download/rel_1/part_ad
          wget https://github.com/Alex9600t/gcc-i686/releases/download/rel_1/part_ae
          wget https://github.com/Alex9600t/gcc-i686/releases/download/rel_1/part_af
          cat part_* > i686-elf-toolchain.tar.gz
          tar -xf i686-elf-toolchain.tar.gz
          tree ./i686-elf
          echo "${GITHUB_WORKSPACE}/i686-elf/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          i686-elf-gcc --version
          i686-elf-ld --version
          make