name: Test
on: push
jobs:
  buildTest:
    runs-on: ubuntu-latest
    steps:
      - name: Download git
        uses: actions/checkout@v3
      - name: install gcc, nasm and ld
        run: sudo apt install gcc gcc-i686-linux-gnu nasm
      - name: build
        run: make