name: Test
on: push
jobs:
  buildTest:
    runs-on: ubuntu-latest
    steps:
      - name: Download git
        uses: actions/checkout@v3
      - name: Update kernel
        run: sudo apt-get update && sudo apt-get install -y
      - name: Download dependencies
        run: sudo apt install gcc gcc-i686-linux-gnu nasm build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo
      - name: Install i686-elf-gcc
        run: |
          wget https://github.com/lordmilko/i686-elf-tools/releases/download/13.2.0/i686-elf-tools-linux.tar.gz
          tar -xzf i686-elf-tools-linux.tar.gz
          echo "${GITHUB_WORKSPACE}/i686-elf-tools-linux/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          i686-elf-gcc --version
          i686-elf-ld --version
          make