name: Test
on: push
jobs:
  buildTest:
    runs-on: ubuntu-latest
    steps:
      - name: Download git
        uses: actions/checkout@v3
      - name: Update kernel
        run: sudo apt-get update && sudo apt-get install -y
      - name: Download dependencies
        run: sudo apt install gcc gcc-i686-linux-gnu nasm build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo
      - name: Install i686-elf-gcc
        run: |
          wget https://github.com/cjacker/gcc-cross-compiler/releases/download/10.2.0-1/x86_64-linux-i686-elf-binutils.tar.gz
          wget https://github.com/cjacker/gcc-cross-compiler/releases/download/10.2.0-1/x86_64-linux-i686-elf-gcc.tar.gz

          tar -xzf x86_64-linux-i686-elf-binutils.tar.gz
          tar -xzf x86_64-linux-i686-elf-gcc.tar.gz

          echo "$GITHUB_WORKSPACE/x86_64-linux-i686-elf-bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/x86_64-linux-i686-elf-gcc/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          i686-elf-gcc --version
          i686-elf-ld --version
          make